version: '3'

services:

    chrome:
        image: selenium/standalone-chrome
        container_name: chrome
        platform: linux/amd64
        ports:
        - 4444:4444
        volumes:
        - /dev/shm:/dev/shm
    
    server:
        platform: linux/amd64
        image: nlp-server
        container_name: nlp-server
        build:
            context: ./server
            dockerfile: Dockerfile
        ports:
        - 8000:8000

    client:
        platform: linux/amd64
        image: nlp-client
        container_name: nlp-client
        build:
            context: ./client
            dockerfile: Dockerfile
        ports:
        - 8501:8501
