version: '3'

services:
    client:
        image: nlp-client
        container_name: nlp-client
        build:
            context: ./client
            dockerfile: Dockerfile
        ports:
        - 8501:8501
    
    server:
        image: nlp-server
        container_name: nlp-server
        build:
            context: ./server
            dockerfile: Dockerfile
        ports:
        - 8000:8000